version: '3.8'

services:
  web:
    build: .
    container_name: php-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
