# When a task that used to pass starts to fail, go through all versions that may have been skipped to detect when the
# task started failing.
stepback: true

# Mark a failure as a system/bootstrap failure (purple box) rather than a task failure by default.
# Actual testing tasks are marked with `type: test`
command_type: system

# Protect ourselves against rogue test case that runs forever. Tasks are killed after 10 minutes, which shouldn't occur
# under normal circumstances.
exec_timeout_secs: 600

# These pre and post rules apply to all tasks not part of a task group, which should only ever be tests against local
# MongoDB instances. All other tasks that require special preparation should be run from within a task group
pre:
  - func: "fetch source"
  - func: "prepare resources"
  - func: "fix absolute paths"
  - func: "init test-results"
  - func: "install dependencies"
  - func: "fetch build"
post:
  - func: "upload test results"
  - func: "stop mongo-orchestration"
  - func: "stop load balancer"
  - func: "cleanup"

# Define aliases for patch builds and PR builds. These only apply if no aliases are defined in project and repo settings
github_pr_aliases: &github_pr_aliases
  # Run all tasks in PR variants for PHP 8.3
  - variant_tags: ["php8.3", "pr"]
    task: ".*"
  # Run PR tasks for PR variants
  - variant_tags: ["pr"]
    task_tags: ["pr"]

commit_queue_aliases: *github_pr_aliases

patch_aliases:
  - alias: pull-request
    variant_tags: ["pr"]
    task_tags: ["pr"]
  - alias: pull-request-latest-php
    variant_tags: ["php8.3", "pr"]
    task: ".*"

# Include files that contain various tasks, task groups, and build variant definitions
include:
  - filename: .evergreen/config/functions.yml

  - filename: .evergreen/config/build-task-groups.yml
  - filename: .evergreen/config/build-variants.yml

  - filename: .evergreen/config/test-tasks.yml

  # Automatically generated files
  - filename: .evergreen/config/generated/build/build-php-8.3.yml
  - filename: .evergreen/config/generated/build/build-php-8.2.yml
  - filename: .evergreen/config/generated/build/build-php-8.1.yml
  - filename: .evergreen/config/generated/build/build-php-8.0.yml
  - filename: .evergreen/config/generated/build/build-php-7.4.yml
  - filename: .evergreen/config/generated/build/build-libmongoc-8.3.yml
  - filename: .evergreen/config/generated/test/local-latest.yml
  - filename: .evergreen/config/generated/test/local-rapid.yml
  - filename: .evergreen/config/generated/test/local-7.0.yml
  - filename: .evergreen/config/generated/test/local-6.0.yml
  - filename: .evergreen/config/generated/test/local-5.0.yml
  - filename: .evergreen/config/generated/test/local-4.4.yml
  - filename: .evergreen/config/generated/test/local-4.2.yml
  - filename: .evergreen/config/generated/test/local-4.0.yml
  - filename: .evergreen/config/generated/test/local-3.6.yml
  - filename: .evergreen/config/generated/test/load-balanced-latest.yml
  - filename: .evergreen/config/generated/test/load-balanced-rapid.yml
  - filename: .evergreen/config/generated/test/load-balanced-7.0.yml
  - filename: .evergreen/config/generated/test/load-balanced-6.0.yml
  - filename: .evergreen/config/generated/test/load-balanced-5.0.yml
  - filename: .evergreen/config/generated/test/ocsp-latest.yml
  - filename: .evergreen/config/generated/test/ocsp-rapid.yml
  - filename: .evergreen/config/generated/test/ocsp-7.0.yml
  - filename: .evergreen/config/generated/test/ocsp-6.0.yml
  - filename: .evergreen/config/generated/test/ocsp-5.0.yml
  - filename: .evergreen/config/generated/test/ocsp-4.4.yml
  - filename: .evergreen/config/generated/test/require-api-version-latest.yml
  - filename: .evergreen/config/generated/test/require-api-version-rapid.yml
  - filename: .evergreen/config/generated/test/require-api-version-7.0.yml
  - filename: .evergreen/config/generated/test/require-api-version-6.0.yml
  - filename: .evergreen/config/generated/test/require-api-version-5.0.yml
  - filename: .evergreen/config/generated/test/skip-crypt-shared-latest.yml
  - filename: .evergreen/config/generated/test/skip-crypt-shared-rapid.yml
  - filename: .evergreen/config/generated/test/skip-crypt-shared-7.0.yml
  - filename: .evergreen/config/generated/test/skip-crypt-shared-6.0.yml
  - filename: .evergreen/config/generated/test-variant/full-php-8.3.yml
  - filename: .evergreen/config/generated/test-variant/full-php-8.2.yml
  - filename: .evergreen/config/generated/test-variant/full-php-8.1.yml
  - filename: .evergreen/config/generated/test-variant/full-php-8.0.yml
  - filename: .evergreen/config/generated/test-variant/full-php-7.4.yml
  - filename: .evergreen/config/generated/test-variant/libmongoc-php-8.3.yml
