tasks:
  - name: "test-atlas-connectivity"
    tags: ["atlas", "nodb", "pr", "tag"]
    commands:
      # This creates secrets-export.sh, which is later sourced by run-tests.sh
      - command: subprocess.exec
        params:
          working_dir: "src"
          binary: bash
          args:
            - -c
            - ${DRIVERS_TOOLS}/.evergreen/secrets_handling/setup-secrets.sh drivers/atlas_connect
      - func: "run tests"
        vars:
          TESTS: "tests/atlas.phpt"

  # Test different storage engines
  - name: "test-mongodb-4.0-standalone-inmemory"
    tags: ["standalone", "local", "4.0", "storage-engines"]
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          MONGODB_VERSION: "4.0"
          STORAGE_ENGINE: "inmemory"
      - func: "run tests"
  - name: "test-mongodb-4.0-standalone-mmapv1"
    tags: ["standalone", "local", "4.0", "storage-engines"]
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          MONGODB_VERSION: "4.0"
          STORAGE_ENGINE: "mmapv1"
      - func: "run tests"
